config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "pages#home"

  resources :users, only: [:show] do
    resources :questionnaires, only: [:new, :create]
  end
  resources :profiles, only: [:show, :new, :create, :edit, :update]
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :user
  belongs_to :job
  validates :user_id, presence: true
  validates :job_id, presence: true
  validates :status, presence: true
  validates :status, inclusion: { in: %w[pending accepted rejected] }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, presence: true
  validates :company, presence: true
  validates :description, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :education_level, presence: true
  validates :job_preference, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true
  validates :description, presence: true
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  belongs_to :user
  validates :industry, :role, :company_size, :work_location, :salary_range, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_one :questionnaire
  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update]

  def show
  end

  def new
    if current_user.profile
      redirect_to edit_profile_path(current_user.profile)
    else
      @profile = Profile.new
    end
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to profile_path(current_user.profile), notice: 'Profile was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to profile_path(current_user.profile), notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_profile
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:education_level, :job_preference, :additional_info)
  end
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_user
  def new
    @questionnaire = Questionnaire.new
    salary_range
    industry
    role
    company_size
    work_location
  end

  def create
    @questionnaire = Questionnaire.new(questionnaire_params)
    @questionnaire.user = @user

    if @questionnaire.save
      redirect_to root_path, notice: 'Go to job suggestions to see what we have found for you!'
    else
      render :new
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def questionnaire_params
    params.require(:questionnaire).permit(:industry, :role, :company_size, :work_location, :salary_range)
  end

  def salary_range
    @salary_range = ["$0 - $50,000", "$50,000 - $100,000", "$100,000 - $150,000", "$150,000 - $200,000", "$200,000+"]
  end

  def industry
    @industry = ["Accounting", "Airlines/Aviation", "Alternative Dispute Resolution", "Alternative Medicine", "Animation", "Apparel & Fashion", "Architecture & Planning", "Arts & Crafts", "Automotive", "Aviation & Aerospace", "Banking", "Biotechnology", "Broadcast Media", "Building Materials", "Business Supplies & Equipment", "Capital Markets", "Chemicals", "Civic & Social Organization", "Civil Engineering", "Commercial Real Estate", "Computer & Network Security", "Computer Games", "Computer Hardware", "Computer Networking", "Computer Software", "Construction", "Consumer Electronics", "Consumer Goods", "Consumer Services", "Cosmetics", "Dairy", "Defense & Space", "Design", "Education Management", "E-learning", "Electrical & Electronic Manufacturing", "Entertainment", "Environmental Services", "Events Services", "Executive Office", "Facilities Services", "Farming", "Financial Services", "Fine Art", "Fishery", "Food & Beverages", "Food Production", "Fundraising", "Furniture"]
  end

  def role
    @role = ["Accountant", "Actuary", "Administrative Assistant", "Advertising Manager", "Analyst", "Architect", "Auditor", "Bank Teller", "Bookkeeper", "Brand Manager", "Budget Analyst", "Business Analyst", "Business Manager", "Cashier", "Chief Executive Officer", "Chief Financial Officer", "Chief Information Officer", "Chief Operating Officer", "Chief Technology Officer", "Civil Engineer", "Consultant", "Controller", "Copywriter", "Customer Service Representative", "Data Analyst", "Data Scientist", "Database Administrator", "Dental Hygienist", "Dentist", "Design Engineer", "Designer", "Developer", "Digital Marketing Manager", "Director", "Editor", "Electrical Engineer", "Engineer", "Engineering Manager", "Executive Assistant", "Financial Advisor", "Financial Analyst", "Financial Manager", "Graphic Designer", "Human Resources Manager", "Information Security Analyst", "Information Technology Manager", "Investment Banker", "IT Director", "IT Manager", "Journalist", "Lawyer", "Legal Assistant", "Librarian", "Loan Officer", "Management Consultant", "Marketing Manager", "Mechanical Engineer", "Medical Assistant", "Medical Technologist", "Nurse", "Occupational Therapist", "Operations Manager", "Paralegal", "Pharmacist", "Physical Therapist", "Physician", "Physician Assistant", "Product Manager", "Program Manager", "Project Manager", "Psychologist", "Public Relations Manager", "Quality Assurance Engineer", "Recruiter", "Registered Nurse", "Research Assistant", "Sales Manager", "Sales Representative", "Software Developer", "Software Engineer", "Speech-Language Pathologist", "Statistician", "Surgeon", "Systems Administrator", "Teacher", "Technical Writer", "Technician", "Therapist", "UX Designer", "Veterinarian", "Web Developer", "Writer"]
  end

  def company_size
    @company_size = ["1-10", "11-50", "51-200", "201-500", "501-1000", "1001-5000", "5001-10,000", "10,001+"]
  end

  def work_location
    @work_location = ["Remote", "On-site", "Hybrid"]
  end
end


# AFTER THEY FILL OUT THE QUESTIONAIRRE, THEY WILL BE REDIRECTED TO THE HOME PAGE
# IT WILL GIVE THEM A NOTICE "PLEASE CHECK JOB_SUGGESTIONS TO SEE WHAT WE HAVE FOUND"

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobFinder</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- FILEPATH: /Users/hamedaljamry/code/Hamed-Aljamry/JobFinder/app/views/pages/home.html.erb -->

  <div class="container">
    <h1>Welcome to Job Finder</h1>
    <p>Find your dream job with ease!</p>
    <%= link_to "New User Questionnaire", new_user_questionnaire_path(current_user), class: "button" %>
  </div>

app/views/profiles/_form.html.erb
<%= simple_form_for @profile do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :education_level %>
    <%= f.input :job_preference %>
    <%= f.input :additional_info %>
    <!-- Add other fields as necessary -->
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<%= render 'form' %>

app/views/profiles/new.html.erb
<%= render 'form' %>

app/views/profiles/show.html.erb
<!-- FILEPATH: /Users/hamedaljamry/code/Hamed-Aljamry/JobFinder/app/views/profiles/show.html.erb -->

<h1>Profile Details</h1>

<p><strong>Education level:</strong> <%= @profile.education_level %></p>
<p><strong>Job preference:</strong> <%= @profile.job_preference %></p>
<p><strong>Additional Information:</strong> <%= @profile.additional_info %></p>


<%= link_to "Edit Profile", edit_profile_path(@profile) %>

app/views/questionnaires/new.html.erb
<%= simple_form_for([@user, @questionnaire]) do |f| %>
<h3>What type of industry are you looking for?</h3>
  <p><%= f.input :industry, collection: @industry, as: :radio_buttons %></p>
  <h3>What type of role are you looking for?</h3>
  <p><%= f.input :role, collection: @role, as: :radio_buttons %></p>
  <h3>What type of company are you looking for?</h3>
  <p><%= f.input :company_size, collection: @company_size, as: :radio_buttons %></p>
  <h3>Where are you looking to work?</h3>
  <p><%= f.input :work_location, collection: @work_location, as: :radio_buttons %></p>
  <h3>What's your salary range</h3>
  <p><%= f.input :salary_range, collection: @salary_range, as: :radio_buttons %></p>
  <%= f.button :submit, "Submit" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "Jobfindr_logo.png", class: "logo", style: "width: 100px; height: auto;" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://st3.depositphotos.com/5266903/13038/v/450/depositphotos_130381916-stock-illustration-call-center-icon-rubber-stamp.jpg", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if current_user.profile %>
                <%= link_to "Profile", profile_path(current_user), class: "dropdown-item" %>
              <% else %>
                <%= link_to "Create Profile", new_profile_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Account Settings", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Account Details</h1>

  <p><strong>Email:</strong><%= @user.email %></p>
  <p><strong>First Name:</strong><%= @user.first_name %></p>
  <p><strong>Last Name:</strong><%= @user.last_name %></p>
  <p><strong>Email:</strong><%= @user.email %></p>